import Foundation

public struct PlaceIconOption: Identifiable, Sendable {
    public let symbol: String
    public let title: String
    public let keywords: String
    public var id: String { symbol }
    public init(_ symbol: String, _ title: String, _ keywords: String) {
        self.symbol = symbol; self.title = title; self.keywords = keywords
    }
}

// Our own place-focused vocabulary. Symbols are rendered by the public system API;
// search uses bundled words, without remote requests or undocumented OS catalogs.
public enum PlaceIconCatalog {
    public static let icons: [PlaceIconOption] = [
        .init("house.fill", "Home", "house apartment flat residence family"),
        .init("briefcase.fill", "Work", "briefcase office job business coworking workplace"),
        .init("building.2.fill", "Office", "work business building city coworking"),
        .init("desktopcomputer", "Desk", "computer office work study workstation coworking"),
        .init("sofa.fill", "Living room", "home lounge sofa couch furniture family"),
        .init("house.and.flag.fill", "Holiday home", "vacation rental house cottage airbnb weekend"),
        .init("cup.and.saucer.fill", "Café", "coffee cafe cup tea breakfast espresso"),
        .init("fork.knife", "Restaurant", "food dinner lunch dining eat meal"),
        .init("wineglass.fill", "Bar", "wine drinks pub alcohol cocktail"),
        .init("birthday.cake.fill", "Bakery", "cake bread pastry dessert birthday sweets"),
        .init("takeoutbag.and.cup.and.straw.fill", "Takeaway", "takeout fast food lunch delivery snack"),
        .init("mug.fill", "Tea room", "tea coffee hot chocolate cafe mug drink"),
        .init("carrot.fill", "Farm", "vegetables produce organic farm garden food"),
        .init("fish.fill", "Seafood", "fish restaurant seafood market fishing"),
        .init("birthday.cake", "Celebration", "birthday party cake wedding anniversary event"),
        .init("basket.fill", "Market", "food shopping groceries basket supermarket"),
        .init("cart.fill", "Supermarket", "shopping groceries food store cart"),
        .init("bag.fill", "Shop", "shopping store retail bag mall"),
        .init("tshirt.fill", "Clothes shop", "clothing fashion clothes shirt shopping boutique"),
        .init("shoe.fill", "Shoe shop", "shoes footwear trainers sneakers shopping"),
        .init("gift.fill", "Gift shop", "gifts presents souvenir shopping birthday"),
        .init("eyeglasses", "Optician", "glasses eyes vision optometrist sunglasses shop"),
        .init("crown.fill", "Jeweller", "jeweler jewellery jewelry ring watch luxury shop"),
        .init("dumbbell.fill", "Gym", "fitness exercise weights workout sport training"),
        .init("figure.yoga", "Yoga", "pilates stretch studio meditation fitness"),
        .init("figure.pool.swim", "Pool", "swimming water swim sport fitness"),
        .init("sportscourt.fill", "Sports court", "tennis basketball football soccer sport club"),
        .init("soccerball", "Football", "soccer stadium sport field match"),
        .init("figure.run", "Running", "run athletics track jogging sport"),
        .init("figure.climbing", "Climbing", "bouldering rocks climb climbing wall sport"),
        .init("figure.skiing.downhill", "Skiing", "ski slopes snow winter mountain sport"),
        .init("figure.snowboarding", "Snowboarding", "snowboard snow winter slopes mountain sport"),
        .init("figure.surfing", "Surfing", "surf waves sea beach water board sport"),
        .init("figure.rower", "Rowing", "row rowing river water boat sport"),
        .init("figure.martial.arts", "Martial arts", "karate judo taekwondo dojo boxing training sport"),
        .init("figure.dance", "Dance studio", "dancing ballet salsa tango class studio"),
        .init("figure.golf", "Golf", "golf course driving range club sport"),
        .init("figure.equestrian.sports", "Stables", "horse riding horses pony equestrian stable"),
        .init("figure.skating", "Skating", "ice skating rink roller skate winter sport"),
        .init("tennis.racket", "Tennis", "tennis padel racket court club sport"),
        .init("basketball.fill", "Basketball", "basketball court hoops stadium sport"),
        .init("volleyball.fill", "Volleyball", "volleyball beach court sport club"),
        .init("baseball.fill", "Baseball", "baseball softball stadium field sport"),
        .init("cricket.ball.fill", "Cricket", "cricket pitch club stadium sport"),
        .init("figure.bowling", "Bowling", "bowling alley pins games leisure"),
        .init("leaf.fill", "Garden", "nature green plants leaf allotment"),
        .init("tree.fill", "Park", "forest trees nature woods green outdoors"),
        .init("mountain.2.fill", "Mountains", "hiking hill nature trail outdoors"),
        .init("beach.umbrella.fill", "Beach", "sea coast sand holiday seaside"),
        .init("water.waves", "Waterfront", "river canal lake ocean sea water"),
        .init("binoculars.fill", "Lookout", "view viewpoint observation sightseeing lookout wildlife"),
        .init("camera.fill", "Photo spot", "photography photos pictures camera sightseeing viewpoint"),
        .init("bird.fill", "Wildlife", "bird birds animals birdwatching reserve nature"),
        .init("ladybug.fill", "Nature reserve", "insects garden conservation wildlife nature reserve"),
        .init("flame.fill", "Campfire", "fire bonfire barbecue bbq camping outdoors"),
        .init("figure.hiking", "Hiking", "hike walk trail trailhead trekking backpack outdoors"),
        .init("sailboat.fill", "Sailing", "sail boat yacht marina harbour harbor water"),
        .init("tent.fill", "Campsite", "camp tent camping outdoors holiday"),
        .init("bed.double.fill", "Hotel", "sleep bed hostel accommodation stay holiday"),
        .init("building.columns.fill", "Museum", "gallery art culture history bank"),
        .init("building.columns", "Bank", "banking atm money cash finance branch"),
        .init("building.columns.circle.fill", "Town hall", "council municipality government city hall civic"),
        .init("person.3.fill", "Community centre", "center community neighbourhood neighborhood meeting club"),
        .init("books.vertical", "Bookshop", "bookstore books reading shopping literature"),
        .init("books.vertical.fill", "Library", "books study read reading education"),
        .init("graduationcap.fill", "School", "education university college study campus"),
        .init("cross.case.fill", "Healthcare", "hospital doctor clinic medical health dentist"),
        .init("pills.fill", "Pharmacy", "medicine drugs health chemist"),
        .init("stethoscope", "Doctor", "gp physician clinic medical healthcare appointment"),
        .init("cross.vial.fill", "Laboratory", "lab blood test clinic medical research science"),
        .init("figure.cooldown", "Physiotherapy", "physio rehabilitation rehab recovery stretch therapy"),
        .init("brain.head.profile", "Therapy", "therapist psychology counselling counseling mental health"),
        .init("shower.fill", "Spa", "wellness sauna shower steam massage relax"),
        .init("heart.fill", "Favourite", "love favorite family partner special"),
        .init("person.2.fill", "Friends", "people family social visit parents"),
        .init("figure.and.child.holdinghands", "Childcare", "nursery daycare kindergarten children school"),
        .init("teddybear.fill", "Playgroup", "toddler baby children toys playgroup playdate"),
        .init("figure.play", "Playground", "children kids play park swings slide"),
        .init("figure.2.and.child.holdinghands", "Family", "parents grandparents relatives family children visit"),
        .init("pawprint.fill", "Pets", "dog cat vet animals pet"),
        .init("dog.fill", "Dog park", "dog dogs puppy walk pets park"),
        .init("cat.fill", "Cat café", "cat cats kitten cafe pets shelter"),
        .init("scissors", "Salon", "hair barber haircut beauty"),
        .init("washer.fill", "Laundry", "washing laundromat clothes cleaning"),
        .init("comb.fill", "Barber", "hair haircut hairdresser barber grooming salon"),
        .init("sparkles", "Beauty", "beautician cosmetics makeup nails manicure salon"),
        .init("hammer.fill", "Hardware shop", "diy tools hardware building repairs home improvement"),
        .init("wrench.and.screwdriver.fill", "Workshop", "repair garage hardware tools maker"),
        .init("paintpalette.fill", "Art studio", "creative paint drawing art design"),
        .init("music.note", "Music", "concert venue band studio rehearsal piano"),
        .init("guitars.fill", "Live music", "guitar guitars band gig concert venue jazz rock"),
        .init("pianokeys", "Music lessons", "piano keyboard lessons practice rehearsal school music"),
        .init("mic.fill", "Karaoke", "singing microphone karaoke comedy open mic"),
        .init("headphones", "Listening room", "music records listening headphones vinyl audio"),
        .init("theatermasks.fill", "Theatre", "theater stage acting culture drama"),
        .init("film.fill", "Cinema", "movie film theater entertainment"),
        .init("ticket.fill", "Event", "festival concert tickets show venue"),
        .init("gamecontroller.fill", "Games", "arcade gaming games play entertainment"),
        .init("dice.fill", "Board games", "boardgames tabletop dice games club chess"),
        .init("puzzlepiece.fill", "Escape room", "puzzle puzzles escape room game challenge"),
        .init("balloon.2.fill", "Party", "balloons birthday celebration kids party venue"),
        .init("bicycle", "Bike stop", "bicycle cycling bike cycle parking"),
        .init("car.fill", "Car park", "car garage parking drive vehicle"),
        .init("tram.fill", "Station", "train tram rail metro subway station transport"),
        .init("bus.fill", "Bus stop", "bus coach public transport station"),
        .init("airplane", "Airport", "plane flight travel terminal aviation"),
        .init("ferry.fill", "Harbour", "harbor boat ferry port sailing transport"),
        .init("lightrail.fill", "Metro", "subway underground metro train public transport station"),
        .init("cablecar.fill", "Cable car", "gondola cablecar ski lift mountain transport"),
        .init("car.rear.fill", "Taxi rank", "taxi cab pickup rideshare car transport"),
        .init("scooter", "Scooter stop", "scooter moped motorbike parking transport"),
        .init("suitcase.rolling.fill", "Luggage", "baggage suitcase lockers storage travel airport"),
        .init("airplane.departure", "Departures", "plane flight leaving departure airport terminal"),
        .init("airplane.arrival", "Arrivals", "plane flight arrival airport terminal pickup"),
        .init("fuelpump.fill", "Fuel stop", "petrol gas gasoline fuel station"),
        .init("bolt.car.fill", "Charging", "electric ev car charging charger energy"),
        .init("bicycle.circle.fill", "Bike shop", "repair bicycle cycling bike shop"),
        .init("envelope.fill", "Post office", "mail parcel shipping delivery letters"),
        .init("shippingbox.fill", "Parcel point", "packages pickup delivery shipping box"),
        .init("truck.box.fill", "Warehouse", "depot storage logistics delivery warehouse distribution"),
        .init("building.2.crop.circle", "Industrial estate", "factory industry business park manufacturing works"),
        .init("antenna.radiowaves.left.and.right", "Broadcast studio", "radio television broadcast station studio media"),
        .init("pc", "Computer shop", "computers electronics laptop repair tech shop"),
        .init("printer.fill", "Print shop", "printing printer copies copy documents stationery"),
        .init("key.fill", "Locksmith", "keys locks key cutting repair security"),
        .init("toilet.fill", "Restroom", "toilets bathroom wc public facilities restroom"),
        .init("waterbottle.fill", "Water refill", "drinking water bottle refill fountain hydration"),
        .init("building.fill", "Building", "apartment property address city"),
        .init("house.lodge.fill", "Cabin", "cottage lodge holiday home chalet"),
        .init("building.2.crop.circle.fill", "City", "town centre center city urban"),
        .init("globe.europe.africa.fill", "Travel", "world country trip holiday vacation"),
        .init("sun.max.fill", "Outdoors", "sun sunshine outside open air"),
        .init("moon.stars.fill", "Night out", "night nightlife evening stars"),
        .init("star.fill", "Special place", "star favorite favourite important"),
        .init("mappin", "Place", "pin location marker destination stop address")
    ]
    public static func search(_ query: String) -> [PlaceIconOption] {
        let words = normalized(query).split { !$0.isLetter && !$0.isNumber }
        return icons.filter { icon in
            let terms = normalized(icon.title + " " + icon.keywords + " " + icon.symbol)
            return words.allSatisfy { terms.contains($0) }
        }
    }
    public static func title(for symbol: String) -> String { icons.first { $0.symbol == symbol }?.title ?? "Custom icon" }
    private static func normalized(_ value: String) -> String {
        value.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX"))
    }
}
