import Foundation

public struct PlaceIconOption: Identifiable, Sendable {
    public let symbol: String
    public let title: String
    public let keywords: String
    public var id: String { symbol }
    public init(_ symbol: String, _ title: String, _ keywords: String) {
        self.symbol = symbol; self.title = title; self.keywords = keywords
    }
}

// Our own place-focused vocabulary. Symbols are rendered by the public system API;
// search uses bundled words, without remote requests or undocumented OS catalogs.
public enum PlaceIconCatalog {
    public static let icons: [PlaceIconOption] = [
        .init("house.fill", "Home", "house apartment flat residence family"),
        .init("briefcase.fill", "Work", "briefcase office job business coworking workplace"),
        .init("building.2.fill", "Office", "office work business building city coworking industrial estate business park factory town kantoor werk stad bedrijventerrein"),
        .init("desktopcomputer", "Desk", "computer office work study workstation coworking"),
        .init("sofa.fill", "Living room", "home lounge sofa couch furniture family"),
        .init("house.and.flag.fill", "Holiday home", "vacation rental house cottage airbnb weekend"),
        .init("cup.and.saucer.fill", "Café", "coffee cafe cup tea breakfast espresso koffie koffiezaak koffiebar cafe καφε καφενειο"),
        .init("fork.knife", "Restaurant", "food dinner lunch dining eat meal"),
        .init("wineglass.fill", "Bar", "wine drinks pub alcohol cocktail bar cafe kroeg wijnbar winery vineyard wine tasting cellar drinks wijngaard wijnproeverij"),
        .init("birthday.cake.fill", "Bakery", "bakery cake bread pastry dessert birthday celebration wedding sweets bakker bakkerij brood taart"),
        .init("takeoutbag.and.cup.and.straw.fill", "Takeaway", "takeaway takeout fast food lunch delivery snack afhaal snackbar"),
        .init("mug.fill", "Tea room", "tea coffee hot chocolate cafe mug drink thee theehuis"),
        .init("carrot.fill", "Vegetables", "vegetables produce organic farm garden supermarket greengrocer groceries groente groenten groenteboer markt garden allotment planting growing gardening moestuin"),
        .init("fish.fill", "Seafood", "fish restaurant seafood market fishing vis viswinkel visboer"),
        .init("basket.fill", "Market", "market food shopping groceries basket supermarket markt boodschappen markthal"),
        .init("cart.fill", "Supermarket", "supermarket shopping groceries food store cart supermarkt boodschappen winkel"),
        .init("bag.fill", "Shop", "shopping store retail bag mall"),
        .init("tshirt.fill", "Clothes shop", "clothing fashion clothes shirt shopping boutique"),
        .init("shoe.fill", "Shoe shop", "shoes footwear trainers sneakers shopping"),
        .init("gift.fill", "Gift shop", "gifts presents souvenir shopping birthday"),
        .init("eyeglasses", "Optician", "glasses eyes vision optometrist sunglasses shop"),
        .init("crown.fill", "Jeweller", "jeweler jewellery jewelry ring watch luxury shop"),
        .init("dumbbell.fill", "Gym", "fitness exercise weights workout sport training"),
        .init("figure.yoga", "Yoga", "pilates stretch studio meditation fitness"),
        .init("figure.pool.swim", "Pool", "swimming water swim sport fitness"),
        .init("sportscourt.fill", "Sports court", "tennis basketball football soccer sport club"),
        .init("soccerball", "Football", "soccer stadium sport field match"),
        .init("figure.run", "Running", "run athletics track jogging sport"),
        .init("figure.climbing", "Climbing", "climbing bouldering wall rocks climb sport klimmen boulderen klimhal"),
        .init("figure.skiing.downhill", "Skiing", "ski slopes snow winter mountain sport"),
        .init("figure.snowboarding", "Snowboarding", "snowboard snow winter slopes mountain sport"),
        .init("figure.surfing", "Surfing", "surfing waves beach board sea sport surfen"),
        .init("figure.rower", "Rowing", "row rowing river water boat sport kayak canoe paddling river boat water kanovaren kano kajak"),
        .init("figure.martial.arts", "Martial arts", "karate judo taekwondo dojo boxing training sport"),
        .init("figure.dance", "Dance studio", "dancing ballet salsa tango class studio"),
        .init("figure.golf", "Golf", "golf course driving range club sport"),
        .init("figure.equestrian.sports", "Stables", "horse riding horses pony equestrian stable"),
        .init("figure.skating", "Skating", "ice skating rink roller skate winter sport"),
        .init("tennis.racket", "Tennis", "tennis padel racket court club sport"),
        .init("basketball.fill", "Basketball", "basketball court hoops stadium sport"),
        .init("volleyball.fill", "Volleyball", "volleyball beach court sport club"),
        .init("baseball.fill", "Baseball", "baseball softball stadium field sport"),
        .init("cricket.ball.fill", "Cricket", "cricket pitch club stadium sport cricket batting wickets sport club pitch"),
        .init("figure.bowling", "Bowling", "bowling alley pins games leisure"),
        .init("leaf.fill", "Garden", "garden nature plants green leaf allotment tuin bloemen planten"),
        .init("tree.fill", "Park", "park forest trees nature woods green outdoors bos bomen natuur tree nursery arborist gardening plants kwekerij boomkwekerij"),
        .init("mountain.2.fill", "Mountains", "hiking hill nature trail outdoors"),
        .init("beach.umbrella.fill", "Beach", "sea coast sand holiday seaside"),
        .init("water.waves", "Waterfront", "river canal lake ocean sea water"),
        .init("binoculars.fill", "Lookout", "view viewpoint observation sightseeing lookout wildlife"),
        .init("camera.fill", "Photo spot", "photography photos pictures camera sightseeing viewpoint"),
        .init("bird.fill", "Wildlife", "bird birds animals birdwatching reserve nature"),
        .init("ladybug.fill", "Nature reserve", "insects garden conservation wildlife nature reserve insecten natuurgebied"),
        .init("flame.fill", "Campfire", "fire bonfire barbecue bbq camping outdoors fire station firefighter emergency brandweer brandweerkazerne"),
        .init("figure.hiking", "Hiking", "hike walk trail trailhead trekking backpack outdoors"),
        .init("sailboat.fill", "Sailing", "sail boat yacht marina harbour harbor water boat rental sailing hire marina bootverhuur sailing club lessons dinghy water sport zeilen zeilclub"),
        .init("tent.fill", "Campsite", "camp tent camping outdoors holiday"),
        .init("bed.double.fill", "Hotel", "sleep bed hostel accommodation stay holiday"),
        .init("building.columns.fill", "Landmark", "museum gallery art culture history town hall municipality government monument bezienswaardigheid gemeentehuis mosque islam worship muslim religion moskee synagogue jewish worship religion synagoge buddhist temple meditation shrine worship boeddhistische tempel hindu temple worship shrine mandir hindoe tempel"),
        .init("person.3.fill", "Community centre", "center community neighbourhood neighborhood meeting club"),
        .init("books.vertical.fill", "Books", "library bookshop bookstore books study read reading education literature bibliotheek boekwinkel boeken"),
        .init("graduationcap.fill", "School", "education university college study campus"),
        .init("cross.case.fill", "Healthcare", "hospital doctor clinic medical health dentist"),
        .init("pills.fill", "Pharmacy", "medicine drugs health chemist"),
        .init("stethoscope", "Doctor", "gp physician clinic medical healthcare appointment"),
        .init("cross.vial.fill", "Laboratory", "lab blood test clinic medical research science"),
        .init("figure.cooldown", "Physiotherapy", "physio rehabilitation rehab recovery stretch therapy"),
        .init("brain.head.profile", "Therapy", "therapist psychology counselling counseling mental health"),
        .init("shower.fill", "Spa", "wellness sauna shower steam massage relax"),
        .init("heart.fill", "Favourite", "love favorite family partner special"),
        .init("person.2.fill", "Friends", "people family social visit parents"),
        .init("figure.and.child.holdinghands", "Childcare", "nursery daycare kindergarten children school"),
        .init("teddybear.fill", "Playgroup", "toddler baby children toys playgroup playdate"),
        .init("figure.play", "Playground", "children kids play park swings slide trampoline jumping bounce park children jump springen"),
        .init("figure.2.and.child.holdinghands", "Family", "parents grandparents relatives family children visit"),
        .init("pawprint.fill", "Pets", "dog cat vet animals pet veterinarian dierenarts huisdieren"),
        .init("dog.fill", "Dog park", "dog dogs puppy walk pets park"),
        .init("cat.fill", "Cat café", "cat cats kitten cafe pets shelter"),
        .init("scissors", "Salon", "hair barber haircut beauty"),
        .init("washer.fill", "Laundry", "washing laundromat clothes cleaning"),
        .init("comb.fill", "Barber", "hair haircut hairdresser barber grooming salon"),
        .init("sparkles", "Beauty", "beautician cosmetics makeup nails manicure salon"),
        .init("hammer.fill", "Hardware shop", "diy tools hardware building repairs home improvement bouwmarkt gereedschap"),
        .init("wrench.and.screwdriver.fill", "Workshop", "repair garage hardware tools maker"),
        .init("paintpalette.fill", "Art studio", "creative painting drawing art design artist kunst atelier schilderen"),
        .init("music.note", "Music", "concert venue band studio rehearsal piano"),
        .init("guitars.fill", "Live music", "guitar guitars band gig concert venue jazz rock"),
        .init("pianokeys", "Music lessons", "piano keyboard lessons practice rehearsal school music"),
        .init("mic.fill", "Microphone", "singing microphone karaoke comedy open mic recording studio podcast radio voice microfoon opnamestudio"),
        .init("headphones", "Listening room", "music records listening headphones vinyl audio record store platenzaak luisteren"),
        .init("theatermasks.fill", "Theatre", "theater stage acting culture drama"),
        .init("film.fill", "Cinema", "movie film theater entertainment"),
        .init("ticket.fill", "Event", "festival concert tickets show venue"),
        .init("gamecontroller.fill", "Games", "arcade gaming games play entertainment"),
        .init("dice.fill", "Board games", "boardgames tabletop dice games club chess"),
        .init("puzzlepiece.fill", "Escape room", "puzzle puzzles escape room game challenge"),
        .init("balloon.2.fill", "Party", "balloons birthday celebration kids party venue"),
        .init("bicycle", "Bicycle", "bicycle cycling bike cycle parking shop repair rental fietsen fiets fietsenmaker fietsenwinkel cycling road racing sport wielrennen wielerclub"),
        .init("car.fill", "Car", "car garage parking drive vehicle taxi cab pickup rideshare auto parkeerplaats car road trip touring travel autorit autorijden car hire rental jeep suv vehicle autoverhuur huurauto"),
        .init("tram.fill", "Station", "train tram rail metro subway underground station transport trein openbaar vervoer tram streetcar stop public transport tramhalte"),
        .init("bus.fill", "Bus stop", "bus coach public transport station"),
        .init("airplane", "Airport", "plane flight travel terminal aviation departures arrivals luchthaven vliegveld vliegtuig aankomst vertrek"),
        .init("ferry.fill", "Harbour", "harbor boat ferry port sailing transport"),
        .init("cablecar.fill", "Cable car", "gondola cablecar ski lift mountain transport"),
        .init("scooter", "Scooter stop", "scooter moped motorbike parking transport"),
        .init("suitcase.rolling.fill", "Luggage", "baggage suitcase lockers storage travel airport"),
        .init("fuelpump.fill", "Fuel stop", "petrol gas gasoline fuel station"),
        .init("bolt.car.fill", "Charging", "electric ev car charging charger energy"),
        .init("envelope.fill", "Post office", "mail parcel shipping delivery letters"),
        .init("shippingbox.fill", "Parcel point", "packages pickup delivery shipping box"),
        .init("truck.box.fill", "Warehouse", "depot storage logistics delivery warehouse distribution"),
        .init("antenna.radiowaves.left.and.right", "Broadcast studio", "radio television broadcast station studio media"),
        .init("pc", "Computer shop", "computers electronics laptop repair tech shop"),
        .init("printer.fill", "Print shop", "printing printer copies copy documents stationery drukkerij printshop kopie"),
        .init("key.fill", "Locksmith", "keys locks key cutting repair security slotenmaker sleutel"),
        .init("toilet.fill", "Restroom", "toilets bathroom wc public facilities restroom"),
        .init("waterbottle.fill", "Water refill", "drinking water bottle refill fountain hydration"),
        .init("building.fill", "Building", "apartment property address city apartment flat residence building condo appartementen flatgebouw"),
        .init("house.lodge.fill", "Cabin", "cottage lodge holiday home chalet mountain hut cabin hikers refuge alpine berghut"),
        .init("globe.europe.africa.fill", "Travel", "world country trip holiday vacation"),
        .init("sun.max.fill", "Outdoors", "sun sunshine outside open air outdoors buiten zon"),
        .init("moon.stars.fill", "Night out", "night nightlife evening stars nacht uitgaan"),
        .init("star.fill", "Special place", "star favorite favourite important"),
        .init("mappin", "Place", "pin location marker destination stop address"),
        .init("laptopcomputer", "Coworking", "laptop coworking computer remote work workspace flexplek kantoor flexwerken digital nomad"),
        .init("scope", "Shooting range", "crosshair shooting archery target range aim shooting club schietbaan boogschieten"),
        .init("pencil.and.scribble", "Writing club", "writing writers author poetry literature journaling creative workshop schrijfclub schrijven dichter"),
        .init("banknote.fill", "Bank", "bank banking atm cash money finance pin geld bankautomaat"),
        .init("figure.fishing", "Fishing", "fishing fish angling lake river hengelen vissen visplek"),
        .init("figure.archery", "Archery", "archery bow arrow target range sport boogschieten boogschietclub"),
        .init("figure.badminton", "Badminton", "badminton racket shuttle court sport badmintonclub"),
        .init("figure.table.tennis", "Table tennis", "table tennis ping pong sport tafeltennis pingpong"),
        .init("figure.boxing", "Boxing", "boxing kickboxing ring gym sport boksen kickboksen"),
        .init("figure.fencing", "Fencing", "fencing swords sword sport schermen schermclub"),
        .init("figure.wrestling", "Wrestling", "wrestling grappling sport worstelen"),
        .init("figure.rugby", "Rugby", "rugby field stadium sport club"),
        .init("figure.handball", "Handball", "handball court sport handbal"),
        .init("figure.disc.sports", "Disc golf", "disc golf frisbee ultimate park field sport"),
        .init("figure.waterpolo", "Water polo", "water polo pool swimming sport waterpolo water polo pool games waterpolo spelen"),
        .init("figure.open.water.swim", "Open-water swim", "open water swim swimming lake beach wild zwemmen open water"),
        .init("figure.stand", "Meeting point", "meeting meetup gathering rendezvous afspreekplek ontmoetingsplek"),
        .init("figure.mind.and.body", "Meditation", "meditation mindfulness retreat zen relax meditatie rust"),
        .init("figure.flexibility", "Stretching", "stretch flexibility mobility fitness class stretchen lenigheid"),
        .init("figure.core.training", "Pilates", "pilates core reformer studio fitness"),
        .init("figure.roll", "Accessibility centre", "wheelchair accessible adapted sport mobility rolstoel toegankelijk"),
        .init("figure.skateboarding", "Skate park", "skateboarding skatepark skate board ramps skateboard"),
        .init("figure.curling", "Curling", "curling ice winter sport curlingbaan"),
        .init("figure.ice.hockey", "Ice hockey", "ice hockey rink winter sport ijshockey"),
        .init("figure.hockey", "Hockey", "field hockey pitch sport hockeyveld"),
        .init("figure.softball", "Softball", "softball field sport honkbal softbal"),
        .init("figure.american.football", "American football", "american football gridiron stadium sport"),
        .init("figure.water.fitness", "Aqua fitness", "aqua aquafit water fitness pool exercise aquarobics"),
        .init("figure.fall", "Trampolining", "gymnastics acrobatics tumbling training turnen gymnastiek"),
        .init("cross.fill", "Memorial", "memorial cemetery grave remembrance begraafplaats herdenking church chapel worship christian religion kerk kapel"),
        .init("frying.pan.fill", "Cooking", "cooking kitchen cookery lessons workshop chef koken kookstudio kookclub"),
        .init("oven.fill", "Kitchen", "kitchen cooking baking chef culinary oven keuken"),
        .init("refrigerator.fill", "Food bank", "food bank groceries donation fridge voedselbank"),
        .init("popcorn.fill", "Popcorn", "popcorn snacks movie cinema snack bioscoop"),
        .init("lightbulb.fill", "Ideas workshop", "ideas invention brainstorming workshop innovation idee creatief brainstorm"),
        .init("paintbrush.pointed.fill", "Drawing class", "drawing illustration sketch artist workshop class tekenen tekenles"),
        .init("paintbrush.fill", "Decorator", "painting decorating decorating business painter schilder schilderwerk"),
        .init("camera.macro", "Flower shop", "flower florist bouquet bloom garden bloemen bloemist bloemenwinkel"),
        .init("photo.artframe", "Gallery", "gallery exhibition art paintings photography kunst galerie expositie"),
        .init("camera.aperture", "Photo studio", "photography photographer portrait photo studio fotograaf fotostudio"),
        .init("video.fill", "Film studio", "video film studio production shoot filmen filmstudio"),
        .init("hifispeaker.fill", "Recording room", "recording studio music speakers audio hi fi hifi opnemen geluidsstudio"),
        .init("radio.fill", "Radio", "radio broadcast station media recording radiozender"),
        .init("newspaper.fill", "Newsroom", "news newspaper journalism editorial newsroom journalist redactie krant"),
        .init("wrench.adjustable.fill", "Plumber", "plumber plumbing pipes repair water loodgieter"),
        .init("screwdriver.fill", "Repair café", "repair cafe fixing repairs volunteer electronics reparatie reparatiecafe tool hire rental diy huren gereedschap gereedschapsverhuur"),
        .init("gearshape.fill", "Factory", "factory manufacturing engineering machines industrial fabriek techniek productie"),
        .init("fan.fill", "Cooling service", "air conditioning fan ventilation repair cooling airco ventilatie"),
        .init("bolt.fill", "Electrician", "electricity electrician electrical repairs power elektricien elektrisch"),
        .init("fossil.shell.fill", "Fossils", "fossils shells geology museum fossielen schelpen"),
        .init("globe.americas.fill", "Embassy", "embassy consulate visa passport travel ambassade consulaat"),
        .init("shield.fill", "Police", "police security station bureau politie politiebureau"),
        .init("bolt.heart.fill", "Emergency care", "emergency urgent care first aid medical ehbo spoed eerste hulp"),
        .init("syringe.fill", "Vaccination", "vaccination vaccines injection travel clinic vaccin prik reisvaccinatie"),
        .init("bandage.fill", "First aid", "first aid wound dressing healthcare bandage verband ehbo"),
        .init("testtube.2", "Science", "science laboratory experiment chemistry lab wetenschap scheikunde"),
        .init("atom", "Research", "research physics science laboratory university onderzoek natuurkunde"),
        .init("ivfluid.bag.fill", "Hospital ward", "hospital ward inpatient infusion medical ziekenhuis afdeling"),
        .init("mouth.fill", "Dentist", "dentist dental teeth orthodontist mond tandarts gebit"),
        .init("lungs.fill", "Breathing clinic", "lungs breathing respiratory clinic lung rehabilitation longen ademhaling"),
        .init("nose.fill", "Fragrance shop", "perfume fragrance scent cosmetics parfum parfumerie"),
        .init("hand.raised.fill", "Volunteering", "volunteer help charity community support vrijwilligers hulp"),
        .init("hands.sparkles.fill", "Cleaning", "cleaner cleaning hygiene housekeeping schoonmaak schoonmaker"),
        .init("hand.thumbsup.fill", "Good spot", "good recommended favourite nice goed leuk aanrader"),
        .init("person.crop.rectangle.fill", "Passport office", "passport identity photo documents town hall paspoort gemeente identiteitsbewijs"),
        .init("wallet.bifold.fill", "Wallet shop", "wallet leather bags accessories portemonnee lederwaren"),
        .init("hanger", "Clothes rack", "clothes wardrobe fashion tailor kleding kleermaker garderobe"),
        .init("button.programmable", "Craft supplies", "buttons crafts sewing haberdashery craft handwerken fournituren naaien"),
        .init("suitcase.fill", "Travel agency", "travel agency luggage holidays tours reisbureau reizen vakantie"),
        .init("motorcycle.fill", "Motorbike", "motorcycle motorbike biker repair rental motor motorfiets"),
        .init("truck.pickup.side.fill", "Pickup", "pickup truck transport vehicle bestelbus transport"),
        .init("bus.doubledecker.fill", "Sightseeing bus", "sightseeing tour bus double decker hop on hop off rondrit touringcar"),
        .init("figure.walk", "Walking club", "walking walk hiking club foot wandelen wandelclub"),
        .init("shoeprints.fill", "Trailhead", "trail walking footsteps route walk pad wandelroute snowshoe snow winter trail sneeuwschoenen"),
        .init("signpost.right.fill", "Junction", "junction crossroads directions route meeting wayfinding kruispunt wegwijzer"),
        .init("parkingsign", "Parking", "parking car garage parking lot parkeerplaats parkeergarage"),
        .init("opticaldisc.fill", "Record shop", "records cds music discs dvd vinyl platenzaak cd winkel"),
        .init("microbe.fill", "Biology lab", "biology microbiology microbes laboratory research biologie"),
        .init("ant.fill", "Ant farm", "ants insect insects nature education mieren insecten"),
        .init("hare.fill", "Petting zoo", "rabbit bunny petting zoo animals children konijn kinderboerderij"),
        .init("tortoise.fill", "Animal sanctuary", "tortoise turtle reptiles animal sanctuary shelter schildpad opvang"),
        .init("lizard.fill", "Reptile house", "reptile lizard zoo terrarium reptiles reptielen hagedis"),
        .init("sprinkler.and.droplets.fill", "Allotment", "allotment irrigation garden community planting volkstuin tuinieren"),
        .init("paperclip", "Stationery", "stationery office supplies paper pens kantoorartikelen papierwaren"),
        .init("battery.100percent", "Battery shop", "batteries power electronics service accu batterij"),
        .init("thermometer.medium", "Weather station", "weather climate temperature meteorology weer weerstation"),
        .init("snowflake", "Cold storage", "ice cold refrigeration freezer cool koelhuis ijsbaan"),
        .init("rainbow", "Pride", "pride rainbow community queer lgbtq festival regenboog"),
        .init("flag.checkered", "Race track", "racing race kart karting motorsport circuit kartbaan racebaan"),
        .init("rosette", "Awards", "award competition ceremony prize show wedstrijd prijzen"),
        .init("medal.fill", "Sports club", "sport club medal competition training trophy sportvereniging"),
        .init("trophy.fill", "Stadium", "stadium arena sports competition final stadion"),
    ]
    public static func search(_ query: String) -> [PlaceIconOption] {
        let words = normalized(query).split { !$0.isLetter && !$0.isNumber }
        return icons.filter { icon in
            let terms = normalized(icon.title + " " + icon.keywords + " " + icon.symbol)
            return words.allSatisfy { terms.contains($0) || PlaceIconMatcher.matchesSearchAlias(String($0), for: icon.symbol) }
        }
    }
    private static let legacySymbols: [String: String] = [
        "birthday.cake": "birthday.cake.fill",
        "building.columns": "banknote.fill",
        "building.columns.circle.fill": "building.columns.fill",
        "books.vertical": "books.vertical.fill",
        "lightrail.fill": "tram.fill",
        "car.rear.fill": "car.fill",
        "airplane.departure": "airplane",
        "airplane.arrival": "airplane",
        "bicycle.circle.fill": "bicycle",
        "building.2.crop.circle": "building.2.fill",
        "building.2.crop.circle.fill": "building.2.fill"
    ]
    public static func canonicalSymbol(_ symbol: String) -> String { legacySymbols[symbol] ?? symbol }
    public static func title(for symbol: String) -> String { icons.first { $0.symbol == canonicalSymbol(symbol) }?.title ?? "Custom icon" }
    private static func normalized(_ value: String) -> String {
        value.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX"))
    }
}
