import Foundation

/// Local, deterministic defaults. A known category outranks a business name;
/// explicit choices in the editor outrank this matcher. Specific phrases precede
/// broad ones, with Unicode word boundaries so “Bar” cannot match “Barbara”.
public enum PlaceIconMatcher {
    private struct Rule: Sendable {
        let symbol: String
        let pattern: String
        let expression: NSRegularExpression
        init(_ symbol: String, _ pattern: String) {
            self.symbol = symbol; self.pattern = pattern
            expression = try! NSRegularExpression(pattern: #"(?<![\p{L}\p{N}])(?:"# + pattern + #")(?![\p{L}\p{N}])"#)
        }
    }
    private static let rules: [Rule] = [
        .init("car.fill", #"car rental|car hire|taxi(?: rank)?|autoverhuur|huurauto|rideshare"#),
        .init("bed.double.fill", #"hotels?|hostels?|resorts?|motel|accommodation|guest\s?house|bed (?:and|&) breakfast|pension|vakantiepark|grecotel"#),
        .init("house.and.flag.fill", #"holiday home|vacation rental|airbnb|vakantiehuis(?:je)?|cottage rental"#),
        .init("house.lodge.fill", #"cabin|chalet|lodge|mountain hut|berghut|berghutte"#),
        .init("house.fill", #"home|thuis|huis|woning|residence|private residence"#),
        .init("building.fill", #"apartments?|appartement(?:en)?|condominium|flatgebouw"#),
        .init("laptopcomputer", #"co[\s-]?working|flexplek|flexwerken|shared workspace|wework|digital nomad|remote work"#),
        .init("briefcase.fill", #"office|offices|work|workplace|kantoor|werk|kantoorpand"#),
        .init("desktopcomputer", #"desk|workstation|computer room|computerlokaal|bureau"#),
        .init("sofa.fill", #"living room|lounge|furniture|woonkamer|meubel(?:zaak|winkel|s)?|ikea"#),
        .init("cup.and.saucer.fill", #"coffee(?:house|shop|bar)?|cafe|cafeteria|espresso|koffie(?:bar|huis|zaak|tent)?|starbucks|καφε|καφενειο"#),
        .init("mug.fill", #"tea\s?room|tea\s?house|tea shop|thee(?:huis|kamer|winkel)?|matcha"#),
        .init("fork.knife", #"restaurants?|dining|diner|bistro|brasserie|taverna|tavern|eetcafe|eetgelegenheid|sushi|pizzeria|pizza|steakhouse|noodles|ramen|εστιατοριο|ταβερνα"#),
        .init("birthday.cake.fill", #"baker(?:y|ies)|bakker(?:ij)?|patisserie|pastry|boulangerie|cake(?:s| shop)?|taart|brood|celebration|birthday"#),
        .init("wineglass.fill", #"bar|pub|kroeg|wine\s?bar|cocktail(?:s| bar)?|drinks|wijnbar|biercafe|taphouse|taproom"#),
        .init("wineglass.fill", #"winery|vineyard|wine tasting|wijngaard|wijnproeverij|wijnhuis|cellar"#),
        .init("takeoutbag.and.cup.and.straw.fill", #"take\s?away|take\s?out|fast food|afhaal|snackbar|snack bar|kebab|friet|frituur|burger|mcdonalds|kfc"#),
        .init("frying.pan.fill", #"cooking|cookery|cooking class|kook(?:studio|club|school)|koken|culinary workshop"#),
        .init("oven.fill", #"kitchen|keuken|commercial kitchen|catering"#),
        .init("refrigerator.fill", #"food bank|voedselbank|community fridge"#),
        .init("carrot.fill", #"greengrocer|vegetables?|produce|groente(?:n|boer|winkel)?|organic food|fruit shop"#),
        .init("cart.fill", #"supermarkets?|supermarkt(?:en)?|grocer(?:y|ies)|albert heijn|jumbo|lidl|aldi|tesco|sainsbury|spar|waitrose|whole foods|carrefour|sklavenitis|boodschappen"#),
        .init("basket.fill", #"market(?:s|place)?|markt(?:hal|en)?|farmers market|boerenmarkt|food hall"#),
        .init("fish.fill", #"seafood|fish(?:monger| market| shop)?|vis(?:boer|winkel|markt)|oyster|seafood restaurant"#),
        .init("tshirt.fill", #"clothes|clothing|fashion|boutique|kleding(?:zaak|winkel)?|modewinkel|vintage clothing"#),
        .init("shoe.fill", #"shoe(?:s| shop| store)?|footwear|sneakers|schoenen(?:winkel)?"#),
        .init("gift.fill", #"gift(?:s| shop)?|souvenir(?:s| shop)?|cadeau(?:s|winkel)?"#),
        .init("eyeglasses", #"optici(?:an|en)|optometrist|eyewear|glasses|brillen(?:winkel)?"#),
        .init("crown.fill", #"jewell?er|jewell?ery|juwelier|sieraden|watch shop|horloges"#),
        .init("bag.fill", #"shops?|stores?|retail|mall|winkel(?:centrum)?|department store|warenhuis"#),
        .init("dumbbell.fill", #"gyms?|fitness|weights|weightlifting|workout|sportschool|sportcentrum|basic fit|trainmore"#),
        .init("figure.yoga", #"yoga|yogastudio|yogaschool"#),
        .init("figure.core.training", #"pilates|reformer|core training"#),
        .init("figure.mind.and.body", #"meditation|mindfulness|retreat|meditatie|zen"#),
        .init("figure.pool.swim", #"swimming pool|swim club|zwembad|zwemclub|pool|swimming"#),
        .init("figure.open.water.swim", #"open water swim|wild swimming|openwaterzwemmen"#),
        .init("figure.waterpolo", #"water\s?polo"#),
        .init("figure.water.fitness", #"aqua\s?(?:fitness|fit|robics)|aquarobics|water aerobics"#),
        .init("soccerball", #"football|soccer|voetbal(?:club|veld)?"#),
        .init("figure.american.football", #"american football|gridiron"#),
        .init("figure.rugby", #"rugby"#),
        .init("basketball.fill", #"basketball|basketbal|hoops"#),
        .init("volleyball.fill", #"volleyball|volleybal|beach volley"#),
        .init("baseball.fill", #"baseball|honkbal"#),
        .init("figure.softball", #"softball|softbal"#),
        .init("cricket.ball.fill", #"cricket"#),
        .init("figure.handball", #"handball|handbal"#),
        .init("figure.hockey", #"field hockey|hockey"#),
        .init("figure.ice.hockey", #"ice hockey|ijshockey"#),
        .init("tennis.racket", #"tennis|padel|squash|racket club"#),
        .init("figure.table.tennis", #"table tennis|tafeltennis|ping\s?pong"#),
        .init("figure.badminton", #"badminton"#),
        .init("figure.golf", #"golf|driving range|golfbaan"#),
        .init("figure.disc.sports", #"disc golf|frisbee|ultimate frisbee"#),
        .init("figure.climbing", #"climbing|boulder(?:ing|en)?|klim(?:men|hal|muur)|rock climbing"#),
        .init("figure.run", #"running|athletics|jogging|hardlopen|atletiek|running track"#),
        .init("figure.hiking", #"hiking|trekking|trailhead|wandelpad|wandelroute"#),
        .init("figure.walk", #"walking club|wandelclub|wandelen|walking"#),
        .init("figure.boxing", #"boxing|kickboxing|boksen|kickboksen|boxing gym"#),
        .init("figure.martial.arts", #"martial arts|karate|judo|taekwondo|dojo|kung fu|jiu jitsu|aikido"#),
        .init("figure.wrestling", #"wrestling|grappling|worstelen"#),
        .init("figure.fencing", #"fencing|schermen|schermclub"#),
        .init("scope", #"shooting(?: range| club)?|schiet(?:baan|club|vereniging)|target shooting|crosshair"#),
        .init("figure.archery", #"archery|boogschieten|boogschietclub"#),
        .init("figure.dance", #"dance|dancing|ballet|salsa|tango|dans(?:school|studio|les|en)"#),
        .init("figure.equestrian.sports", #"stables?|horse riding|equestrian|manege|paardrijden|ruitersport"#),
        .init("figure.skating", #"skating rink|ice skating|roller skating|schaats(?:baan|en)|schaatshal"#),
        .init("figure.skateboarding", #"skate\s?park|skateboarding|skateboard"#),
        .init("figure.bowling", #"bowling(?: alley)?|bowlingbaan"#),
        .init("figure.skiing.downhill", #"ski(?:ing| slope| resort)?|skieen|skipiste|skigebied"#),
        .init("figure.snowboarding", #"snowboard(?:ing)?"#),
        .init("shoeprints.fill", #"snowshoe(?:ing)?|sneeuwschoenen"#),
        .init("figure.curling", #"curling"#),
        .init("figure.surfing", #"surf(?:ing| school)?|surfen|surfschool|windsurfing|kitesurfing"#),
        .init("figure.rower", #"kayak(?:ing)?|canoe|canoeing|kano(?:varen)?|kajak"#),
        .init("figure.rower", #"row(?:ing|ing club)?|roeien|roeiclub|roeivereniging"#),
        .init("figure.fishing", #"fishing|angling|hengelen|visvereniging|visplek"#),
        .init("figure.play", #"trampoline(?: park)?|jump park|trampolining"#),
        .init("figure.fall", #"gymnastics|acrobatics|tumbling|turnen|gymnastiek"#),
        .init("sportscourt.fill", #"sports court|sport court|sporthal|sports hall|sports centre"#),
        .init("trophy.fill", #"stadium|arena|stadion"#),
        .init("medal.fill", #"sports club|sportvereniging|sportclub"#),
        .init("leaf.fill", #"garden|gardens|botanical|tuin|tuinen|hortus|botanisch"#),
        .init("sprinkler.and.droplets.fill", #"allotment|volkstuin|moestuin|community garden"#),
        .init("tree.fill", #"park|forest|woods|bos|arboretum|tree nursery|boomkwekerij"#),
        .init("mountain.2.fill", #"mountain|mountains|hill|bergen|berg|summit"#),
        .init("beach.umbrella.fill", #"beach|beaches|strand|coast|seaside|παραλια"#),
        .init("water.waves", #"waterfront|riverside|lakeside|river|canal|meer|rivier|gracht"#),
        .init("binoculars.fill", #"lookout|viewpoint|observation deck|uitkijk(?:punt|toren)|panorama"#),
        .init("bird.fill", #"birdwatching|bird hide|vogel(?:kijkhut|spotten)|wildlife"#),
        .init("ladybug.fill", #"nature reserve|conservation|natuurgebied|natuurreservaat"#),
        .init("tent.fill", #"campsite|campground|camping|kamperen|tent site"#),
        .init("flame.fill", #"campfire|bonfire|fire station|brandweer|kampvuur|barbecue|bbq"#),
        .init("sailboat.fill", #"sailing|sailboat|yacht|marina|boat rental|boat hire|zeil(?:en|club)|bootverhuur|jachthaven"#),
        .init("building.columns.fill", #"museum|museums|monument|town hall|city hall|gemeentehuis|municipality|landmark"#),
        .init("photo.artframe", #"gallery|exhibition|galerie|expositie|art gallery"#),
        .init("banknote.fill", #"bank|banking|atm|geldautomaat|pin(?:automaat)?|cashpoint"#),
        .init("person.3.fill", #"community (?:center|centre)|meeting hall|buurthuis|wijkcentrum|community club"#),
        .init("books.vertical.fill", #"library|libraries|bookshop|bookstore|reading club|book club|books|bibliotheek|boek(?:winkel|handel|enclub)|leesclub"#),
        .init("pencil.and.scribble", #"writing club|writers?|writing|poetry|author|journal(?:ing)?|schrijv(?:en|er|ers)|schrijf(?:club|groep)|dicht(?:club|er|ers)|literature club"#),
        .init("graduationcap.fill", #"school|university|college|campus|universiteit|hogeschool|education"#),
        .init("stethoscope", #"doctor|physician|gp|huisarts|huisartsen|medical practice"#),
        .init("mouth.fill", #"dentist|dental|orthodontist|tandarts|tandartsen|mondzorg"#),
        .init("pills.fill", #"pharmacy|pharmacies|chemist|apotheek|apotheken|drugstore|φαρμακειο"#),
        .init("bolt.heart.fill", #"emergency care|urgent care|spoedeisende hulp|emergency room"#),
        .init("bandage.fill", #"first aid|ehbo|eerste hulp"#),
        .init("cross.case.fill", #"hospital|clinic|healthcare|ziekenhuis|kliniek|gezondheidscentrum"#),
        .init("syringe.fill", #"vaccination|vaccine|vaccinatie|reisvaccinatie|travel clinic"#),
        .init("cross.vial.fill", #"blood test|bloedprikken|medical laboratory"#),
        .init("figure.cooldown", #"physiotherapy|physio|fysiotherapie|fysio|rehabilitation|revalidatie"#),
        .init("brain.head.profile", #"therapy|therapist|psychologist|counselling|counseling|psycholoog|therapie"#),
        .init("shower.fill", #"spa|wellness|sauna|massage|steam room|hammam"#),
        .init("figure.and.child.holdinghands", #"childcare|nursery|daycare|kindergarten|kinderopvang|creche|bso"#),
        .init("teddybear.fill", #"playgroup|toddler|peuterspeelzaal|speelgroep|baby class"#),
        .init("figure.play", #"playground|play area|speeltuin|speelplaats|indoor play"#),
        .init("figure.2.and.child.holdinghands", #"family|parents|grandparents|familie|ouders|opa|oma"#),
        .init("person.2.fill", #"friends|vrienden|vriendin|vriend"#),
        .init("pawprint.fill", #"pets|pet shop|vet|veterinar(?:y|ian)|dierenarts|dierenwinkel|animal hospital"#),
        .init("dog.fill", #"dog park|dog walking|puppy|honden(?:park|veld|school)|hond"#),
        .init("cat.fill", #"cat cafe|cat shelter|katten(?:cafe|opvang)|kat"#),
        .init("hare.fill", #"petting zoo|kinderboerderij|rabbit|konijn"#),
        .init("tortoise.fill", #"animal sanctuary|animal rescue|schildpad|turtle|tortoise"#),
        .init("lizard.fill", #"reptile|reptiles|reptile house|reptielen|terrarium"#),
        .init("comb.fill", #"barber|barbershop|barbier|herenkapper"#),
        .init("scissors", #"hairdresser|haircut|hair salon|kapper|kapsalon"#),
        .init("sparkles", #"beauty|beautician|cosmetics|makeup|nails|manicure|schoonheidssalon|nagelstudio|salon"#),
        .init("washer.fill", #"laundry|laundromat|dry cleaning|wasserette|wasserij|stomerij"#),
        .init("hands.sparkles.fill", #"cleaning|cleaner|housekeeping|schoonmaak|schoonmaker"#),
        .init("hammer.fill", #"hardware|diy|home improvement|bouwmarkt|ijzerwaren|gamma|praxis|hornbach"#),
        .init("wrench.adjustable.fill", #"plumber|plumbing|loodgieter"#),
        .init("bolt.fill", #"electrician|electrical repair|elektricien"#),
        .init("screwdriver.fill", #"repair cafe|reparatiecafe|tool rental|gereedschapsverhuur"#),
        .init("wrench.and.screwdriver.fill", #"workshop|repair shop|garage|werkplaats|reparatie"#),
        .init("gearshape.fill", #"factory|manufacturing|engineering|fabriek|productie|machines"#),
        .init("paintpalette.fill", #"art studio|artist|atelier|art class|kunst|painting|schilderen"#),
        .init("paintbrush.pointed.fill", #"drawing class|drawing|illustration|sketch|teken(?:les|club|en)"#),
        .init("paintbrush.fill", #"decorator|decorating|schilder|schildersbedrijf"#),
        .init("camera.macro", #"florist|flower shop|flowers|bloemist|bloemen(?:winkel)?"#),
        .init("camera.aperture", #"photo studio|photography studio|photographer|fotograaf|fotostudio"#),
        .init("camera.fill", #"photo spot|photography|photos|fotografie|fotoplek"#),
        .init("video.fill", #"film studio|video production|filmstudio|filming"#),
        .init("mic.fill", #"recording studio|podcast|microphone|microfoon|opnamestudio|karaoke|open mic|comedy|studio"#),
        .init("hifispeaker.fill", #"listening room|hifi|hi fi|geluidsstudio|audio room"#),
        .init("radio.fill", #"radio|broadcast|radiozender|radiostation"#),
        .init("guitars.fill", #"live music|gig|jazz|guitar|guitars|gitaar|band rehearsal"#),
        .init("pianokeys", #"piano|music lessons|muziekles|pianoles"#),
        .init("headphones", #"record shop|record store|vinyl|platenzaak|listening"#),
        .init("music.note", #"music|concert|rehearsal|muziek|concertzaal"#),
        .init("theatermasks.fill", #"theat(?:re|er)|drama|acting|toneel|schouwburg"#),
        .init("film.fill", #"cinema|movies|movie theater|bioscoop|filmhuis"#),
        .init("ticket.fill", #"festival|event|ticket|evenement|venue"#),
        .init("dice.fill", #"board\s?games|tabletop|chess|schaak(?:club)?|bordspel(?:len)?|spelletjesclub"#),
        .init("gamecontroller.fill", #"arcade|gaming|video games|game club|games"#),
        .init("puzzlepiece.fill", #"escape\s?room|puzzle|puzzel"#),
        .init("balloon.2.fill", #"party|feest|feestzaal|party venue"#),
        .init("bicycle", #"bicycles?|bikes?|cycling|bike shop|fiets(?:en|enmaker|enwinkel|verhuur)?|wielerclub|wielrennen"#),
        .init("parkingsign", #"parking|car park|parkeer(?:plaats|garage|terrein)|park and ride"#),
        .init("car.fill", #"car|auto|vehicle|taxi"#),
        .init("tram.fill", #"rail(?:way)? station|train station|metro|subway|underground|tram|station|trein|tramhalte"#),
        .init("bus.fill", #"bus|bus stop|coach station|busstation|bushalte"#),
        .init("airplane", #"airport|airline|aviation|airfield|aerodrome|flight|airplane|luchthaven|vliegveld|vliegtuig|schiphol|αεροδρομιο"#),
        .init("ferry.fill", #"ferry|harbou?r|port|veer(?:boot|pont)|haven|λιμανι"#),
        .init("cablecar.fill", #"cable car|gondola|ski lift|kabelbaan|skilift"#),
        .init("motorcycle.fill", #"motorcycle|motorbike|motorfiets|motorclub"#),
        .init("scooter", #"scooter|moped|brommer|bromfiets"#),
        .init("suitcase.rolling.fill", #"luggage|baggage|lockers|bagage|koffer"#),
        .init("fuelpump.fill", #"fuel|petrol|gas station|gasoline|tankstation|benzine|shell|bp"#),
        .init("bolt.car.fill", #"ev charging|charging station|electric charging|laadpaal|laadstation|supercharger"#),
        .init("envelope.fill", #"post office|postkantoor|postnl|postal|mail office"#),
        .init("shippingbox.fill", #"parcel|package pickup|pakketpunt|pakket|delivery point"#),
        .init("truck.box.fill", #"warehouse|depot|logistics|magazijn|distributiecentrum|opslag"#),
        .init("pc", #"computer shop|electronics|computer repair|computerwinkel|elektronica"#),
        .init("printer.fill", #"print shop|printing|copies|copy shop|drukkerij|printshop|kopie"#),
        .init("paperclip", #"stationery|office supplies|kantoorartikelen|papierwaren"#),
        .init("key.fill", #"locksmith|keys|key cutting|slotenmaker|sleutelservice"#),
        .init("toilet.fill", #"toilet|toilets|restroom|bathroom|wc|sanitair"#),
        .init("waterbottle.fill", #"water refill|drinking water|water fountain|drinkwater|watertappunt"#),
        .init("cross.fill", #"church|chapel|cathedral|kerk|kapel|kathedraal"#),
        .init("building.columns.fill", #"mosque|moskee|masjid"#),
        .init("building.columns.fill", #"synagogue|synagoge|jewish temple"#),
        .init("building.columns.fill", #"buddhist|buddhist temple|boeddhistisch|stupa"#),
        .init("building.columns.fill", #"hindu temple|mandir|hindoe"#),
        .init("cross.fill", #"cemetery|memorial|graveyard|begraafplaats|herdenking"#),
        .init("globe.americas.fill", #"embassy|consulate|ambassade|consulaat"#),
        .init("shield.fill", #"police|politie|politiebureau|police station"#),
        .init("hand.raised.fill", #"volunteer|charity|vrijwilliger|vrijwilligers|charitable"#),
        .init("newspaper.fill", #"newsroom|newspaper|journalism|redactie|krant"#),
        .init("testtube.2", #"science|laboratory|chemistry|scheikunde|wetenschap|lab"#),
        .init("atom", #"research|physics|onderzoek|natuurkunde"#),
        .init("flag.checkered", #"race track|racetrack|kart(?:ing)?|go kart|kartbaan|circuit|racebaan"#),
        .init("suitcase.fill", #"travel agency|reisbureau|tour operator"#),
        .init("sun.max.fill", #"outdoors|outside|buiten"#),
        .init("moon.stars.fill", #"nightclub|night club|nightlife|nachtclub|discotheek"#),
        .init("rainbow", #"pride|lgbtq|queer community|regenboog"#)
    ]

    public static func suggestedSymbol(name: String, category: String? = nil) -> String? {
        if let category, let symbol = match(category) { return symbol }
        return match(name)
    }
    private static func match(_ value: String) -> String? {
        let text = normalized(String(value.prefix(512)))
        // Multiword matches beat broad words (“table tennis” over “tennis”).
        // Equal specificity keeps the curated priority: Airport Café is a café.
        var best: (symbol: String, words: Int)?
        for rule in rules {
            guard let match = rule.expression.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)),
                  let range = Range(match.range, in: text) else { continue }
            let words = text[range].split { !$0.isLetter && !$0.isNumber }.count
            if words > (best?.words ?? 0) { best = (rule.symbol, words) }
        }
        return best?.symbol
    }
    private static let rulesBySymbol = Dictionary(grouping: rules, by: \.symbol)
    static func matchesSearchAlias(_ value: String, for symbol: String) -> Bool {
        let text = normalized(String(value.prefix(512)))
        let range = NSRange(text.startIndex..., in: text)
        return rulesBySymbol[symbol]?.contains { $0.expression.firstMatch(in: text, range: range) != nil } ?? false
    }
    private static func normalized(_ text: String) -> String {
        text.folding(options: [.diacriticInsensitive, .caseInsensitive, .widthInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            .lowercased().replacingOccurrences(of: "_", with: " ").replacingOccurrences(of: "ς", with: "σ")
    }
}
